### ISSUE TITLE
cannot cancel second order

### ISSUE THREAD

**Issue by rleyhh** [ericls/huobi#1]
For example, there are two submitted orders:1234 and 5678.
And I use submit_cancel(order_id=1234), order 1234 is successfully canceled.
Then I use submit_cancel(order_id=5678), error shows that I am cancelling order 1234, failed.
Ask for help, please.

**Comment by ericls** [comment]
Hi rleyhh,

Thanks for testing this library reaching out.
I'll take a look shortly.

**Comment by ericls** [comment]
@rleyhh that was a stupid mistake in the code. fixed in 9ddbcf6 and published `0.1.10` to pypi
