### ISSUE TITLE
Huobi API authentication change

### ISSUE THREAD

**Issue by mutedstack** [ericls/huobi#11]
Must change authentication before July 23rd, 2018 23:59:59 （GMT+8 Beijing）.

> User is required to create a Private Key and Public Key. Private Key is kept by user, while the Public Key should be provided to Huobi. (as Section 1, 2 in Details below)

> Besides the existing ‘Signature’, User should also calculate a ‘PrivateSignature’ with the Private Key (section 3.3 in detail steps below). And both ‘Signature’ and ‘PrivateSignature’ should be included in the Query Request. (section 4 in detail steps below)

From https://github.com/huobiapi/API_Docs_en/wiki/Signing_API_Requests .

```python
params['PrivateSignature'] = createPrivateSignature(signature)

# ...

def createPrivateSignature(context):
    data = bytes(context, encoding='utf8')
    # Read the pri_key_file
    digest = hashes.Hash( hashes.SHA256(), default_backend())

    digest.update(data)
    dgst = digest.finalize()
    skey = load_pem_private_key( PRIVATE_KEY, password=None, backend=default_backend())

    sig_data = skey.sign( data, ec.ECDSA(hashes.SHA256()))
    sig_r, sig_s = decode_dss_signature(sig_data)

    sig_bytes = b''
    key_size_in_bytes = bit_to_bytes(skey.public_key().key_size)
    sig_r_bytes = sig_r.to_bytes(key_size_in_bytes, "big")
    sig_bytes += sig_r_bytes
    #print("ECDSA signature R: {:s}".format(sig_r_bytes.hex()))
    sig_s_bytes = sig_s.to_bytes(key_size_in_bytes, "big")
    sig_bytes += sig_s_bytes
  #  print("ECDSA signature S: {:s}".format(sig_s_bytes.hex()))
    # print("ECDSA signautre: {:s}".format(sig_bytes.hex()))
    #print("ECDSA signautre: " + str(base64.b64encode(sig_bytes)))
    return base64.b64encode(sig_bytes)
```

[REST-Python3-demo](https://github.com/huobiapi/REST-API-demos/blob/master/REST-Python3-demo/Utils.py).

**Comment by ericls** [comment]
Thank you for reporting, this is very important. Will fix asap

**Comment by ericls** [comment]
Closing this issue because the current authentication method still works for huobi pro
