### ISSUE TITLE
Can't use auto-completion for client attributes 

### ISSUE THREAD

**Issue by mutedstack** [ericls/huobi#2]
For example, if you type `client.place`, then the IDE should remind you with all the params in the `Endpoint` of place.

**Comment by ericls** [comment]
Hey Jay,

Thanks for reaching out.
This is actually something I wanted to do from the begining! But I was having problem figuring out how to change the signatures of returned functions.  Do you have any suggestions on how to achieve this?

I will definitely go back to it and try to figure it out. In the mean time, the kwargs should be documented in the doc string already though it's not ideal as a proper auto-completion.

Cheers

**Comment by ericls** [comment]
I was able to add signature to endpoints in e435a7773b68680a708c7043d38f290cae305780 but it doesn't seem to help autocompletion.

**Comment by ericls** [comment]
closing stagnant discussion. Feel free to re-open
