### ISSUE TITLE
Lack development requirements

### ISSUE THREAD

**Issue by mutedstack** [ericls/huobi#6]
Lack development requirements such as `python-dotenv` for tests.

I wanted to add it to `setup.py`'s `install_requires` and using `pip-compile`, but I think that development requirements aren't required for production.

So how about add a `dev-requirements.txt` with 

```
-r requirements.txt
python-dotenv==0.8.2
```

**Comment by ericls** [comment]
400d07ea309dc7bc75fb953ddf507c3592678b05
